# Generated by Django 4.1 on 2024-09-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantsImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
