# Generated by Django 4.1 on 2024-09-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0002_plantsimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
