# Generated by Django 4.1 on 2024-09-08 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0004_remove_plants_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='expert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='polenovo.expert'),
        ),
    ]
