# Generated by Django 4.1 on 2024-09-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0005_expert_team_expert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantsImport',
        ),
    ]
