# Generated by Django 4.1 on 2024-09-08 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0006_delete_plantsimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('points', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polenovo.plants')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='plants',
            field=models.ManyToManyField(through='polenovo.CheckList', to='polenovo.plants'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polenovo.team'),
        ),
    ]
