# Generated by Django 4.1 on 2024-09-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0007_checklist_team_plants_checklist_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='phone',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
