# Generated by Django 4.1 on 2024-09-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0008_expert_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='plants',
            field=models.ManyToManyField(related_name='team', through='polenovo.CheckList', to='polenovo.plants'),
        ),
    ]
