# Generated by Django 4.1 on 2024-09-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0009_alter_team_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('РВ', 'Разновозрастные'), ('В', 'Взрослые'), ('Э', 'Эксперты'), ('М', 'Младшие школьники')], default=None, max_length=300),
        ),
    ]
