# Generated by Django 4.1 on 2024-09-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0010_team_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='points',
            field=models.CharField(choices=[('В', 'До вида'), ('С', 'До семейства'), ('Н', 'Не определено')], default='Н', max_length=30),
        ),
    ]
