# Generated by Django 4.1 on 2024-09-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0011_alter_checklist_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='points',
            new_name='success',
        ),
    ]
