# Generated by Django 4.1 on 2024-09-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0012_rename_points_checklist_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='success',
        ),
        migrations.AddField(
            model_name='checklist',
            name='fam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='vid',
            field=models.BooleanField(default=False),
        ),
    ]
