# Generated by Django 4.1 on 2024-09-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0013_remove_checklist_success_checklist_fam_checklist_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='fam',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='vid',
        ),
        migrations.AddField(
            model_name='checklist',
            name='suc',
            field=models.IntegerField(default=0),
        ),
    ]
