# Generated by Django 4.1 on 2024-09-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0016_checklist_fam_checklist_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='res',
        ),
    ]
