# Generated by Django 4.1 on 2024-09-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0017_remove_checklist_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='plantN',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
