# Generated by Django 4.1 on 2024-09-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polenovo', '0018_checklist_plantn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='plantN',
            new_name='N',
        ),
    ]
